// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGlmCspH3QrmX2bl9Tsn6Hv9-AUy3r-I',
    appId: '1:240828262239:web:09b5fe439f3482ab00f8ea',
    messagingSenderId: '240828262239',
    projectId: 'fooddeliverytute-f59ca',
    authDomain: 'fooddeliverytute-f59ca.firebaseapp.com',
    storageBucket: 'fooddeliverytute-f59ca.firebasestorage.app',
    measurementId: 'G-QTLH4SWKDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAeNvjqfD-pp9bljX-tuvMi9JNj9GISQ',
    appId: '1:240828262239:android:af71ee0e445ab70500f8ea',
    messagingSenderId: '240828262239',
    projectId: 'fooddeliverytute-f59ca',
    storageBucket: 'fooddeliverytute-f59ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8mcVWy77mukNO0nliJsqP7ymceaXaoNE',
    appId: '1:240828262239:ios:940cf0c7e3fe81b100f8ea',
    messagingSenderId: '240828262239',
    projectId: 'fooddeliverytute-f59ca',
    storageBucket: 'fooddeliverytute-f59ca.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8mcVWy77mukNO0nliJsqP7ymceaXaoNE',
    appId: '1:240828262239:ios:940cf0c7e3fe81b100f8ea',
    messagingSenderId: '240828262239',
    projectId: 'fooddeliverytute-f59ca',
    storageBucket: 'fooddeliverytute-f59ca.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsGlmCspH3QrmX2bl9Tsn6Hv9-AUy3r-I',
    appId: '1:240828262239:web:0db8c091c1d753d900f8ea',
    messagingSenderId: '240828262239',
    projectId: 'fooddeliverytute-f59ca',
    authDomain: 'fooddeliverytute-f59ca.firebaseapp.com',
    storageBucket: 'fooddeliverytute-f59ca.firebasestorage.app',
    measurementId: 'G-6EY7XQ4YQH',
  );
}
